#!/usr/bin/env python3
"""Build the single public stylesheet from ordered source modules.

The source modules are intentionally kept separate while the migration settles.
Public pages must only link to /style.css. This builder preserves the historical
cascade order and hoists/deduplicates CSS @import rules so they remain valid.
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / "style.css"
MODULES = (
    "styles/base.css",
    "comparison-pages.css",
    "brand-pages.css",
    "design-v2.css",
    "design-v2-rollout.css",
    "assets/product-cards.css",
    "assets/inline-affiliate.css",
    "home-model-polish.css",
    "model-pages-v3.css",
    "home-hero-refresh.css",
)
# Match a complete @import line. URLs such as Google Fonts legitimately contain
# semicolons in their query string, so do not stop matching at the first ';'.
IMPORT_RE = re.compile(r"^[ \t]*@import\s+[^\r\n]*;[ \t]*$", re.M)


def clean_trailing_whitespace(text: str) -> str:
    return "\n".join(line.rstrip() for line in text.splitlines())


def build() -> str:
    imports: list[str] = []
    sections: list[str] = []

    for rel in MODULES:
        path = ROOT / rel
        if not path.exists():
            raise SystemExit(f"Missing CSS module: {rel}")
        css = path.read_text(encoding="utf-8")

        for match in IMPORT_RE.findall(css):
            rule = match.strip()
            if rule not in imports:
                imports.append(rule)
        css = IMPORT_RE.sub("", css)
        css = clean_trailing_whitespace(css).strip()

        sections.append(
            "\n".join(
                (
                    "/* ============================================================",
                    f"   SOURCE MODULE: {rel}",
                    "   ============================================================ */",
                    css,
                )
            )
        )

    header = "\n".join(
        (
            "/* ============================================================",
            "   ASPIRATEURS CHANTIER — GENERATED SINGLE STYLESHEET",
            "   Do not edit this file directly. Edit the source modules and run:",
            "   python _build_css.py",
            "   ============================================================ */",
        )
    )
    import_block = "\n".join(imports)
    chunks = [header]
    if import_block:
        chunks.extend(("", import_block))
    chunks.extend(("", "\n\n".join(sections), ""))
    return "\n".join(chunks)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail when style.css is stale")
    args = parser.parse_args()

    bundled = build()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != bundled:
            raise SystemExit("style.css is stale; run: python _build_css.py")
        print("CSS bundle: PASS")
        return

    OUTPUT.write_text(bundled, encoding="utf-8")
    print(f"CSS bundle written: {OUTPUT.name} ({len(bundled):,} bytes, {len(MODULES)} modules)")


if __name__ == "__main__":
    main()
